const Classroom = require("../models/classroom");
const { findStudentSeat, normalizeStoredSeating } = require("../utils/seating");

async function mySeat(req, res) {
  try {
    const student = req.user;
    const classroom = await Classroom.findOne({ classesAllowed: student.className });
    if (!classroom) return res.status(404).json({ error: "No classroom found for your class" });

    if (!Array.isArray(classroom.seatingPlan) || !classroom.seatingPlan.length) {
      return res.status(404).json({ error: "Seating has not been generated by admin yet" });
    }

    const seating = normalizeStoredSeating(classroom.seatingPlan);
    const seat = findStudentSeat(seating, student._id);
    if (!seat) return res.status(404).json({ error: "Seat not assigned" });

    return res.json({
      classroom: classroom.name,
      seat,
      seating,
      seatingGeneratedAt: classroom.seatingGeneratedAt,
      seatingVersion: classroom.seatingVersion || 0,
      lastSeatingAction: classroom.lastSeatingAction || ""
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}

module.exports = { mySeat };
