const mongoose = require("mongoose");
const Classroom = require("../models/classroom");
const Attendance = require("../models/Attendance");
const CheatingIncident = require("../models/CheatingIncident");
const { moveStudent, normalizeStoredSeating } = require("../utils/seating");

async function myHall(req, res) {
  try {
    if (!req.user.assignedClassroom) return res.status(404).json({ error: "No assigned classroom" });

    const classroom = await Classroom.findById(req.user.assignedClassroom);
    if (!classroom) return res.status(404).json({ error: "Classroom not found" });

    if (!Array.isArray(classroom.seatingPlan) || !classroom.seatingPlan.length) {
      return res.status(404).json({ error: "Seating has not been generated by admin yet" });
    }

    return res.json({
      classroom: classroom.name,
      seating: normalizeStoredSeating(classroom.seatingPlan),
      antiCheat: classroom.antiCheatReport || null,
      seatingGeneratedAt: classroom.seatingGeneratedAt,
      seatingVersion: classroom.seatingVersion || 0,
      lastSeatingAction: classroom.lastSeatingAction || ""
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}

async function markAttendance(req, res) {
  try {
    const { studentId, status } = req.body;
    if (!studentId || !mongoose.Types.ObjectId.isValid(studentId) || !["present", "absent"].includes(status)) {
      return res.status(400).json({ error: "studentId and status (present/absent) required" });
    }
    if (!req.user.assignedClassroom) return res.status(400).json({ error: "Teacher has no classroom assigned" });

    await Attendance.create({
      classroom: req.user.assignedClassroom,
      teacher: req.user._id,
      student: studentId,
      status
    });
    return res.json({ ok: true });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}

async function reportIncident(req, res) {
  try {
    const { studentId, severity, notes, row, bench, seat } = req.body;
    if (!studentId) return res.status(400).json({ error: "studentId required" });
    if (!req.user.assignedClassroom) return res.status(400).json({ error: "Teacher has no classroom assigned" });

    const classroom = await Classroom.findById(req.user.assignedClassroom);
    if (!classroom) return res.status(404).json({ error: "Classroom not found" });
    if (!Array.isArray(classroom.seatingPlan) || !classroom.seatingPlan.length) {
      return res.status(400).json({ error: "Seating has not been generated by admin yet" });
    }

    const incident = await CheatingIncident.create({
      classroom: req.user.assignedClassroom,
      teacher: req.user._id,
      student: studentId,
      severity: Number(severity || 1),
      notes: notes || ""
    });

    let relocation = null;
    if (row && bench && seat) {
      const moved = moveStudent(classroom.seatingPlan, studentId, { row, bench, seat });
      classroom.seatingPlan = moved.seating;
      classroom.seatingGeneratedAt = new Date();
      classroom.seatingVersion = Number(classroom.seatingVersion || 0) + 1;
      classroom.lastSeatingAction = "teacher-relocation-after-incident";
      await classroom.save();
      relocation = {
        from: moved.from,
        to: moved.to,
        swappedStudent: moved.swappedStudent
      };
    }

    return res.json({
      ok: true,
      id: incident._id,
      relocation,
      adminVisible: true
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}

module.exports = { markAttendance, myHall, reportIncident };
